services:
  - type: web
    name: bot-vinted-iphone
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: GUILD_ID
        sync: false
      - key: INTERVAL_SECONDS
        value: 60
      - key: LOW_FACTOR
        value: 0.27
      - key: MIN_MODEL
        value: iphone-12-mini
      - key: EPHEMERAL_CHROME
        value: 1
      - key: DEALS_ONLY
        value: true
